### ISSUE TITLE
Duplicate key errors

### ISSUE THREAD

**Issue by mikeshultz** [mikeshultz/whatthediff#25]
```
Traceback (most recent call last):
  File "/var/www/virtualenvs/whatthediff/lib64/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/virtualenvs/whatthediff/lib64/python3.4/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "./whatthecollection/views.py", line 30, in new_collection
    collection_user = CollectionUser.objects.create(user=request.user, collection=collection, can_write=True)
  File "/var/www/virtualenvs/whatthediff/lib64/python3.4/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/var/www/virtualenvs/whatthediff/lib64/python3.4/site-packages/django/db/models/query.py", line 348, in create
    obj.save(force_insert=True, using=self.db)
  File "/var/www/virtualenvs/whatthediff/lib64/python3.4/site-packages/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/var/www/virtualenvs/whatthediff/lib64/python3.4/site-packages/django/db/models/base.py", line 762, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/var/www/virtualenvs/whatthediff/lib64/python3.4/site-packages/django/db/models/base.py", line 846, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/var/www/virtualenvs/whatthediff/lib64/python3.4/site-packages/django/db/models/base.py", line 885, in _do_insert
    using=using, raw=raw)
  File "/var/www/virtualenvs/whatthediff/lib64/python3.4/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/var/www/virtualenvs/whatthediff/lib64/python3.4/site-packages/django/db/models/query.py", line 920, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/var/www/virtualenvs/whatthediff/lib64/python3.4/site-packages/django/db/models/sql/compiler.py", line 974, in execute_sql
    cursor.execute(sql, params)
  File "/var/www/virtualenvs/whatthediff/lib64/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/var/www/virtualenvs/whatthediff/lib64/python3.4/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/var/www/virtualenvs/whatthediff/lib64/python3.4/site-packages/django/utils/six.py", line 658, in reraise
    raise value.with_traceback(tb)
  File "/var/www/virtualenvs/whatthediff/lib64/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: duplicate key value violates unique constraint "whatthecollection_collectionuser_pkey"
DETAIL:  Key (collection_user_id)=(6) already exists.

< 2015-12-16 04:44:19.752 UTC >LOG:  statement: BEGIN
< 2015-12-16 04:44:19.753 UTC >LOG:  statement: INSERT INTO "whatthecollection_collection" ("name") VALUES ('Another Collection') RETURNING "whatthecollection_collection"."collection_id"
< 2015-12-16 04:44:19.753 UTC >LOG:  statement: COMMIT
< 2015-12-16 04:44:19.755 UTC >LOG:  statement: BEGIN
< 2015-12-16 04:44:19.755 UTC >LOG:  statement: INSERT INTO "whatthecollection_collectionuser" ("collection_id", "user_id", "default", "can_write") VALUES (19, 1, false, true) RETURNING "whatthecollection_collectionuser"."collection_user_id"
< 2015-12-16 04:44:19.755 UTC >ERROR:  duplicate key value violates unique constraint "whatthecollection_collectionuser_pkey"
< 2015-12-16 04:44:19.755 UTC >DETAIL:  Key (collection_user_id)=(6) already exists.
```

**Comment by mikeshultz** [comment]
It could be due to a problem with possibly saving collection_user twice.  Once on `create` and once on `save`.
